### ISSUE TITLE
Components are constantly re-rendered 

### ISSUE THREAD

**Issue by moretti** [skidding/cosmos#133]
If you clone `cosmos-example` and add a `console.log` in the render method of `SimpleButton.jsx` you will notice that every component is constantly re-rendered:

![screen shot 2015-05-28 at 17 52 59](https://cloud.githubusercontent.com/assets/1186409/7865836/6e002716-0563-11e5-9af8-266b0d01f9f8.png)

Is there any way to prevent that?

**Comment by skidding** [comment]
> Is there any way to prevent that?

Currently, not really. The only time when this stops is when you focus on the fixture editor. When you're not focused on the fixture editor ComponentPlayground polls the loaded component for state changes and updates the fixture contents every 100ms...

... even when the state didn't change, which is were the problem lies.

Now, the thing is the props for the loaded component don't change, but the component renders because the parent (ComponentPlayground) renders. Why does the parent render? Because of the setState (3rd link below). But it shouldn't re-render if the state is the same.

So a quick solution might be to implement a [PureRenderMixin](https://facebook.github.io/react/docs/pure-render-mixin.html) implementation for ComponentPlayground.shouldComponentPlayground, but with deep comparison. My only worry is that it might be less performant to deep compare entire fixture (props/state) trees every 100ms than to trickle down the render without DOM changes to apply as a result, but I might be wrong.

FYI, here is the relevant code:
- [Where the interval is set](https://github.com/skidding/react-component-playground/blob/master/src/components/component-playground.jsx#L261)
- [When the update is ignored](https://github.com/skidding/react-component-playground/blob/master/src/components/component-playground.jsx#L343-L347)
- [How fixture contents are updated with component state](https://github.com/skidding/react-component-playground/blob/master/src/components/component-playground.jsx#L349-L356)

**Comment by moretti** [comment]
Thank you for the detailed response! Much appreciated!
Perhaps we could represent the `ComponentPlayground`'s state using something like Immutable.js, so that it would be trivial to implement `shouldComponentUpdate`?

**Comment by skidding** [comment]
> Perhaps we could represent the `ComponentPlayground`'s state using something like Immutable.js, so that it would be trivial to implement `shouldComponentUpdate`?

Yes, that thought went through my mind more than once, but I have zero experience with immutability and until recently myself and the company I work at were the only Cosmos users.

Sound like a good time to learn. Let me know if you have any ideas or insights :dancers:

**Comment by skidding** [comment]
@moretti fixed this in `react-component-playground@0.3.1`: https://github.com/skidding/react-component-playground/pull/17

Remove `cosmos-js` from node modules, install again and should no longer render endlessly. Let me know if doesn't work as extended.
