### ISSUE TITLE
Configure port and host of the server

### ISSUE THREAD

**Issue by w0rm** [skidding/cosmos#139]
I need to dockerize cosmos, but I can't, because it only listens on localhost, not '0.0.0.0'. 
What would be a preferred way to set port and host of the server? I am willing to work on this feature.

**Comment by skidding** [comment]
I prefer the config more than the cli args. Out the back of my head, I'm thinking:

1. Abstract [the getUserConfig part](https://github.com/skidding/cosmos/blob/master/component-playground/config.js#L16-L25) into a lib so that it can be reused
2. Use it [in the bin file](https://github.com/skidding/cosmos/blob/master/bin/component-playground.js#L18) to override the `localhost:8989` settings
3. These settings could be set under `userConfig.server.[hostname|port]`, except they would be just properties and not a method like the webpack config (hopefully it's not too confusing to be different)

What do you think? I'm open to other suggestions as well.
