### ISSUE TITLE
editor droppings trigger cosmos

### ISSUE THREAD

**Issue by faassen** [skidding/cosmos#144]
cosmos tries to load `foo.jsx~` (note tilde) and then reports on it containing something with a file extension it cannot interpret. That's not a surprise as it's an Emacs editor dropping.

I'd be nice if Cosmos only tried to auto-load files that are valid extensions (`.js`, `.jsx`) in fixtures, and just ignored the other ones. Or alternatively if I had a way to configure it to ignore particular file patterns entirely, i.e. `*~`.

Note that emacs creates a tilde file as soon as you start typing, and it was kind of surprising to see cosmos jump into action even though I hadn't saved yet. For a moment I was "how does it even know? is hot loader *that* magical?" until I realized what was going on. :)

**Comment by skidding** [comment]
I managed to reproduce and find the source of the problem, but I don't have a solution yet.

When we [require the component class for a fixture](https://github.com/skidding/cosmos/blob/master/component-playground/lib/get-component-fixture-tree.js#L15), webpack creates a [dynamic require context](http://webpack.github.io/docs/context.html) for all files from the components folder. It the require were `require('components/' + componentName + '.jsx')` we wouldn't have this problem, but some React components (namely ES6 classes) use `.js` extensions, and I can't think of a way to fit a `.jsx?` regexp in this require statement. 

We could create a context by hand, like `requireComponent = require.context('components', true, /\.jsx?$/)`, but then we'd have to append the component file extension when we do `requireComponent(componentName)`, because for some reason [resolve extensions](https://github.com/skidding/cosmos/blob/master/component-playground/config.js#L47) don't apply to context requires. So this doesn't work either.

Any ideas?

**Comment by skidding** [comment]
This was probably solved by the latest changes. In any case, it can be improved by customizing [get-component-fixture-tree.js](https://github.com/skidding/cosmos/blob/master/webpack-boilerplate/react-0.13/playground/get-component-fixture-tree.js). Check out the new docs: https://github.com/skidding/cosmos/tree/master/webpack-boilerplate/react-0.13

**Comment by skidding** [comment]
@faassen this patch should be a fix for your problem: https://github.com/skidding/cosmos/pull/180
