### ISSUE TITLE
Children Components

### ISSUE THREAD

**Issue by nivoc** [skidding/cosmos#171]
I found in the closed issues that it is possible to compose components with React.createElement within the fixture.js-Files.

But the disadvantage is that this definitions are not accessible in the web-interface. It's there a way to reference other fixtures directly like:

{
  "icon": "plus",
  "title": "Button with Icon"
  "children": otherComponen.defaultFixture
}

Where otherFixure.default points to a other specific fixture file and the child gets created based on the instructions in there?

**Comment by skidding** [comment]
> It's there a way to reference other fixtures directly like:

Is it possible via `require` calls, but they won't be seen in the interface editor, which only shows serializable properties of the fixture.

The vision is replace the simple fixture editor with a fully featured editor which can read source files instead of just serializable JSON, then you'll be able to do `require`s between fixtures, even write adhoc functions for props. But this is still a bit far in the future for now.

**Comment by nivoc** [comment]
Thanks for the update. Yes require works for me :)
