### ISSUE TITLE
ES6 exported components are not required properly

### ISSUE THREAD

**Issue by RaitoBezarius** [skidding/cosmos#183]
Hi there,

I wanted to say beforehand: WOW! I was thinking of a tool like this FOR AGES.
And WOW, many thanks! :rocket: 

So let's move on the topic:

It seems like that when you load the component by `requireComponent(componentPath)`, if this is an ES6 exported class by `export default` or even `export class MyClass`, it won't work as expected because the result will be an object like the following one:

```js
{
    MyComponent: function MyComponent(),
    __esmodule: true,
    default: function MyComponent()
}
```

So basically, I don't know how we could abstract this in your code.

Maybe let's test that `React.isValidElement(Class)` or something like this.

Furthermore, there is a question of testability if the component is using a decorator like `reduxForm` or anything that depends on the context.

My rule of thumb in my code is to decorate the default export and let the named export undecorated so that it can be tested.
It would translate into `component = component[componentName] || component.default` in my opinion.

What do you think?

**Comment by skidding** [comment]
Hi @RaitoBezarius, thanks for your nice words!

Regarding your situation, this PR is half the solution already: https://github.com/skidding/cosmos/pull/181, right?

I would love to add support for this use case, I was just expecting a broken example before merging the fix, because I'm still using Babel 5 and ES6 classes already for for me. @narenranjit said he will provide this *broken* example, but probably didn't manage to get the time. Maybe the best solution is to upgrade to Babel 6 upfront. Either way, help is appreciated!

**Comment by RaitoBezarius** [comment]
Yeah, it sounds like that it's half the solution.

On the another note, I have already made a fix on my fork, which is "battle-tested" and used in my code. Would you like me to open a PR for it?

I'll try to look if I can reproduce easily in a minimal project!

**Comment by skidding** [comment]
> On the another note, I have already made a fix on my fork, which is "battle-tested" and used in my code. Would you like me to open a PR for it?

Sounds good, yes.

**Comment by patrick-mcdougle** [comment]
Due to the merge on Mar 3, can this issue be closed?

**Comment by skidding** [comment]
> Due to the merge on Mar 3, can this issue be closed?

Yes!
