### ISSUE TITLE
Error with default project of cosmos ("react-transform-catch-errors does not look like a React component")

### ISSUE THREAD

**Issue by bbirand** [skidding/cosmos#187]
Hi, and thanks for cosmos!

I've been trying to integrate it with my project. After many unsuccessful attempts, I decided to try the default project in the git repo. But that's not working for me either.

```
$ git clone https://github.com/skidding/cosmos.git
$ cd cosmos/webpack-boilerplate/react-0.14/
$ npm install
$ npm run playground

> cosmos-webpack-boilerplate@1.0.0 playground /Users/myuser/tmp/cosmos/webpack-boilerplate/react-0.14
> node devServer.js --env playground

Listening at localhost:8989
webpack built e9b51a1d880c5c8c9380 in 7891ms
```

Then when I go to `http://localhost:8989/`, I see this error in the console:
```
index.js:26 Uncaught Error: imports[1] for react-transform-catch-errors does not look like a React component.
```

I am doing this using Chrome Version 51.0.2704.103 (64-bit), on Mac OS X.

Any ideas why this is not working?

**Comment by bbirand** [comment]
OK, the offending package is `redbox-react`. When I change its version in package.json to be exactly "1.1.1", things seem to work.

Not sure how to deal with this as far as cosmos is concerned. This is clearly not an issue here, but it does impact the users of this project. Maybe have the version be pinned exactly?

**Comment by skidding** [comment]
> This is clearly not an issue here, but it does impact the users of this project. Maybe have the version be pinned exactly?

@bbirand actually, it is a problem here as well because the boilerplate doesn't work for newcomers. It would be great if you made a PR for pinning the `redbox-react` package version. Even more, I'd pin all dependencies (either allowing patches via `~` or fixed version altogether) to make sure the boilerplate will continue to work out of the box in the future. I've come to the conclusion that relying on everybody to respect semver is foolish.

Let me know, if you don't have the time I'll try to do it myself as soon as I manage. Thanks!

**Comment by bbirand** [comment]
Hi @skidding, sorry for the late reply. As you may have imagined, I am fairly busy these days. So if you want to take a stab at it, please be my guest! I'll also try to get back to front-end work soon, I'll let you know if I can get to it!

**Comment by catalinmiron** [comment]
@bbirand I've upgraded the dependecies https://github.com/skidding/cosmos/pull/188

**Comment by skidding** [comment]
Closing this per @catalinmiron's [fix](https://github.com/skidding/cosmos/pull/188). @bbirand feel free to reopen if you continue to experience the problem. Thanks!
