### ISSUE TITLE
Batched fetching

### ISSUE THREAD

**Issue by petehunt** [skidding/cosmos#33]
If I nest a Person inside of a Movie, there are going to be 2 serial fetches (which discourages composition due to the perf hit).

Instead, if `getDataUrl()` were a static function of the route (rather than an instance method of the props) it could be called recursively before the components are rendered so you can fetch all of the data you need to.

**Comment by skidding** [comment]
As honored as I am for having an issue opened by @petehunt, this is no longer relevant as the Cosmos project evolved into something that *supports* React components instead of dictating their design (besides the need to be encapsulated).

Pete–whatever you may be doing at the moment, if you ever get another chance to check out the new project mission feel free to check out the (simplified) README: https://github.com/skidding/cosmos/blob/master/README.md
